add the possiblity to use a contributors team instead of authors with years
dune-gdt/pylicense3 pull request #26
Opened 2022-11-15 13:27 UTC by TiKeil

2022-11-15 14:14 UTC, renefritze commented on pylicense3/cli.py
> +        target.write(prefix + f' Contributors team: {authors}\n')
What do you think about giving the user even more flexibility here? 
```suggestion
        target.write(f' {prefix} {authors}\n')
```
So not even the "Contributors team" would be hard coded.

2022-11-15 14:14 UTC, renefritze commented on pylicense3/cli.py
> +        authors = get_git_authors(filename, root)
```suggestion
    authors = getattr(config, 'contributors_team', get_git_authors(filename, root)
```

2022-11-15 14:16 UTC, renefritze commented
I'll have a look at the breaking CI tomorrow. Most likely cause I transferred the repo today.

2022-11-25 10:36 UTC, TiKeil commented on pylicense3/cli.py
> +    authors = getattr(config, 'contributors_team', get_git_authors(filename, root)
```suggestion
    authors = getattr(config, 'contributors_team', get_git_authors(filename, root))
```

2022-11-25 10:37 UTC, TiKeil commented
Thanks for your comments !

2022-11-25 10:40 UTC, renefritze requested changes
I think you applied the suggestion with my missing end paren.

2022-11-25 10:41 UTC, renefritze approved these changes
Disregard previous review, you already fixed my mistake :)

2022-11-25 10:42 UTC, TiKeil commented
Yes. I will add another commit regarding the user flexibility of the team name

2022-11-25 10:44 UTC, renefritze commented
> Yes. I will add another commit regarding the user flexibility of the team name

Great. Feel free to merge and tag for release then. Thanks!

2022-11-25 10:55 UTC, merged